title: 0-fold Cross-Validation
author:
  name: Alexej Gossmann
  email: 0foldcv@pm.me
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Blogging aspirations: machine learning, statistics, deep learning,
  math, theory, application, coding, creativity.

# Build settings

theme: minima

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar
  - jekyll-paginate-v2

# Jekyll-paginate-v2 configuration
# See https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page:num/' # Pages are index.html inside this folder (default)
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

# Jekyll-scholar configuration
scholar:
  style: apa #ieee-with-url
  sort_by: year, month
  order: descending
  source: ./_bibliography
  bibliography: references.bib  # name of the default bibliography used to add references within posts
  bibliography_template: bib  # bib.html in _layouts
  repository: ./assets/pdf  # When generating bibliographies, Jekyll-Scholar will look in that folder to see if it contains a filename matching each entry's BibTeX key: if it does, the path to that file will be exposed to the bibliography template as the link property.

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
      - { platform: github,         user_url: "https://github.com/agisga" }
      - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=PBNVF8cAAAAJ" }
      - { platform: linkedin,       user_url: "https://www.linkedin.com/in/alexejgossmann" }
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #   - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:
  shortname: agisga

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics: UA-94080131-1  # analytics is no longer useful for me

# From https://jekyllrb.com/docs/usage/:
# If you want to build for your production environment:
# * Set your production URL in `_config.yml` e.g. `url: https://example.com.`
# * Run `JEKYLL_ENV=production bundle exec jekyll build`
url: https://www.alexejgossmann.com

# Set the permalink structure globally
permalink: /:title/

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - papers.md
  - about.md
#  - microblog.md
# "Blog" and "Microblog" links are included by default, see `_includes/header.html`

# Set to `true` to show excerpts on the homepage.
#
show_excerpts: true
